language: go

go:
  - 1.x

matrix:
  fast_finish: true

before_install:
  - make install

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always